import { Beat } from "@/lib/types";

// Generate pseudo-random waveform data seeded by string
function generateWaveform(seed: string, length = 80): number[] {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    hash = ((hash << 5) - hash + seed.charCodeAt(i)) | 0;
  }
  const data: number[] = [];
  for (let i = 0; i < length; i++) {
    hash = ((hash * 1103515245 + 12345) & 0x7fffffff);
    const val = 0.2 + (hash % 1000) / 1000 * 0.8;
    data.push(val);
  }
  return data;
}

// ===== Mock Beat Data =====
export const MOCK_BEATS: Beat[] = [
  {
    id: "beat-1",
    producerId: "prod-1",
    producerName: "NIGHTOWL",
    producerAvatar: "",
    title: "Midnight Drip",
    description: "Dark, atmospheric trap beat with heavy 808s and ethereal pads.",
    genres: ["Trap", "Hip Hop"],
    tags: ["dark", "atmospheric", "808", "moody"],
    formats: ["mp3", "wav", "flac", "stems"],
    bpm: 140,
    key: "Cm",
    duration: 198,
    prices: { mp3: 19.99, wav: 39.99, flac: 49.99, stems: 99.99 },
    previewUrl: "/samples/trap-dark.mp3",
    waveformData: generateWaveform("midnight-drip"),
    coverArtUrl: "",
    avgRating: 4.8,
    reviewCount: 124,
    salesCount: 567,
    createdAt: new Date("2026-07-15"),
    isActive: true,
  },
  {
    id: "beat-2",
    producerId: "prod-2",
    producerName: "VELVET KEYS",
    producerAvatar: "",
    title: "Golden Hour",
    description: "Smooth R&B beat with warm keys and silky drums.",
    genres: ["R&B", "Soul"],
    tags: ["smooth", "warm", "soulful", "chill"],
    formats: ["mp3", "wav", "flac"],
    bpm: 85,
    key: "Eb",
    duration: 224,
    prices: { mp3: 14.99, wav: 29.99, flac: 39.99, stems: 79.99 },
    previewUrl: "/samples/rnb-smooth.mp3",
    waveformData: generateWaveform("golden-hour"),
    coverArtUrl: "",
    avgRating: 4.6,
    reviewCount: 89,
    salesCount: 412,
    createdAt: new Date("2026-07-20"),
    isActive: true,
  },
  {
    id: "beat-3",
    producerId: "prod-3",
    producerName: "BASSQUAKE",
    producerAvatar: "",
    title: "Neon District",
    description: "Hard-hitting drill beat with aggressive slides and punchy kicks.",
    genres: ["Drill", "Hip Hop"],
    tags: ["drill", "aggressive", "hard", "slides"],
    formats: ["mp3", "wav", "stems"],
    bpm: 145,
    key: "F#m",
    duration: 180,
    prices: { mp3: 24.99, wav: 44.99, flac: 54.99, stems: 119.99 },
    previewUrl: "/samples/drill-hard.mp3",
    waveformData: generateWaveform("neon-district"),
    coverArtUrl: "",
    avgRating: 4.9,
    reviewCount: 203,
    salesCount: 891,
    createdAt: new Date("2026-07-25"),
    isActive: true,
  },
  {
    id: "beat-4",
    producerId: "prod-1",
    producerName: "NIGHTOWL",
    producerAvatar: "",
    title: "Purple Haze",
    description: "Lo-fi dreamy beat with vinyl crackle and mellow chords.",
    genres: ["Lo-Fi", "Hip Hop"],
    tags: ["lofi", "chill", "dreamy", "vinyl"],
    formats: ["mp3", "wav", "flac"],
    bpm: 78,
    key: "Am",
    duration: 210,
    prices: { mp3: 9.99, wav: 24.99, flac: 34.99, stems: 69.99 },
    previewUrl: "/samples/lofi-chill.mp3",
    waveformData: generateWaveform("purple-haze"),
    coverArtUrl: "",
    avgRating: 4.5,
    reviewCount: 67,
    salesCount: 298,
    createdAt: new Date("2026-07-28"),
    isActive: true,
  },
  {
    id: "beat-5",
    producerId: "prod-4",
    producerName: "AFROWAVE",
    producerAvatar: "",
    title: "Lagos Nights",
    description: "Infectious Afrobeats instrumental with log drums and shakers.",
    genres: ["Afrobeats", "Dancehall"],
    tags: ["afrobeats", "dancehall", "tropical", "groovy"],
    formats: ["mp3", "wav", "flac", "stems"],
    bpm: 105,
    key: "G",
    duration: 195,
    prices: { mp3: 19.99, wav: 34.99, flac: 44.99, stems: 89.99 },
    previewUrl: "/samples/afrobeats-groove.mp3",
    waveformData: generateWaveform("lagos-nights"),
    coverArtUrl: "",
    avgRating: 4.7,
    reviewCount: 156,
    salesCount: 723,
    createdAt: new Date("2026-08-01"),
    isActive: true,
  },
  {
    id: "beat-6",
    producerId: "prod-5",
    producerName: "SYNTHWAVE9000",
    producerAvatar: "",
    title: "Electric Dreams",
    description: "Retro-futuristic pop beat with synth arps and crisp snares.",
    genres: ["Pop", "EDM"],
    tags: ["synthwave", "retro", "pop", "energetic"],
    formats: ["mp3", "wav", "flac", "stems"],
    bpm: 120,
    key: "Bb",
    duration: 216,
    prices: { mp3: 14.99, wav: 29.99, flac: 39.99, stems: 79.99 },
    previewUrl: "/samples/synthpop-retro.mp3",
    waveformData: generateWaveform("electric-dreams"),
    coverArtUrl: "",
    avgRating: 4.4,
    reviewCount: 45,
    salesCount: 189,
    createdAt: new Date("2026-08-02"),
    isActive: true,
  },
  {
    id: "beat-7",
    producerId: "prod-2",
    producerName: "VELVET KEYS",
    producerAvatar: "",
    title: "Silk Road",
    description: "Boom bap beat with dusty samples and hard-hitting drums.",
    genres: ["Boom Bap", "Hip Hop"],
    tags: ["boombap", "oldschool", "dusty", "classic"],
    formats: ["mp3", "wav"],
    bpm: 92,
    key: "Dm",
    duration: 186,
    prices: { mp3: 12.99, wav: 27.99, flac: 37.99, stems: 74.99 },
    previewUrl: "/samples/boombap-dusty.mp3",
    waveformData: generateWaveform("silk-road"),
    coverArtUrl: "",
    avgRating: 4.7,
    reviewCount: 112,
    salesCount: 534,
    createdAt: new Date("2026-08-03"),
    isActive: true,
  },
  {
    id: "beat-8",
    producerId: "prod-3",
    producerName: "BASSQUAKE",
    producerAvatar: "",
    title: "Phantom",
    description: "Haunting trap beat with ghostly vocal chops and deep bass.",
    genres: ["Trap"],
    tags: ["dark", "haunting", "trap", "vocal"],
    formats: ["mp3", "wav", "flac", "stems"],
    bpm: 135,
    key: "Em",
    duration: 204,
    prices: { mp3: 22.99, wav: 42.99, flac: 52.99, stems: 109.99 },
    previewUrl: "/samples/trap-phantom.mp3",
    waveformData: generateWaveform("phantom"),
    coverArtUrl: "",
    avgRating: 4.8,
    reviewCount: 178,
    salesCount: 812,
    createdAt: new Date("2026-08-04"),
    isActive: true,
  },
  {
    id: "beat-free-1",
    producerId: "prod-1",
    producerName: "BeatVault Originals",
    producerAvatar: "",
    title: "Genesis (Free Demo Sampler)",
    description: "Free starter beat with full WAV stems and MP3 demo for non-commercial evaluation and mixing practice.",
    genres: ["Hip Hop", "Lo-Fi"],
    tags: ["free", "starter", "demo", "sample"],
    formats: ["mp3", "wav", "flac"],
    bpm: 120,
    key: "C",
    duration: 160,
    prices: { mp3: 0.00, wav: 0.00, flac: 0.00, stems: 0.00 },
    previewUrl: "/samples/hiphop-free.mp3",
    waveformData: generateWaveform("genesis-free"),
    coverArtUrl: "",
    avgRating: 5.0,
    reviewCount: 342,
    salesCount: 4520,
    createdAt: new Date("2026-08-05"),
    isActive: true,
    isFree: true,
  },
];
